### ISSUE TITLE
Waar komt metadata-categorie Nijmegen vandaan?

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#28]
Dit komt helemaal niet voor in het corpus, maar is wel te selecteren bij Regio onder Geavanceerd zoeken

**Comment by signfuse** [comment]
Dit komt waarschijnlijk uit de beginmaanden toen ik testwaarden nodig had.
Ik heb het verwijderd maar zal de lijst nog moeten aanpassen zodat het zoeken klopt.

**Comment by ocrasborn** [comment]
Voor de duidelijkheid: de zeven waardes die er moeten komen te staan, staan wel correct in de Woordenlijst 'Regio': Amsterdam, Groningen, Rotterdam, St. Michielsgestel, Voorburg, Overig, Gemengd; graag in die volgorde op het zoekformulier, en niet helemaal alfabetisch

**Comment by signfuse** [comment]
@ocrasborn het is aangepast.
Ik heb St. Michielsgestel wel ingekort naar Michielsgestel op het label, is dat ok?
Zo nee, moet ik de labels wat langer maken, of het font verkleinen.

**Comment by ocrasborn** [comment]
@signfuse  Nee, dat is een wat rare afkorting, maar gebruik deze maar, die is heel breed bekend: "Gestel"

**Comment by signfuse** [comment]
In orde!

Ik heb trouwens al lang een synoniemenlijst in de zoekmachine op de voorpagina staan.
Ik heb er nu Gestel aan toegevoegd. Ik geef de lijst hier mee, misschien heb je nog ideeën voor synoniemen;

var geslachtMan = ["man", "baas", "basserool", "bink", "broger", "gast", "heer", "heerschap", "kadee", "kerel", "kinkel", "manspersoon", "meneer", "mijnheer", "pief", "snuiter", "vent"];
    var geslachtVrouw = ["vrouw", "dame", "juffrouw", "mannin", "mevrouw", "vrouwmens", "vrouwspersoon", "wijf"];
    var regioAmsterdam = ["amsterdam", "adam", "ams"];
    var regioGroningen = ["groningen", "grun", "grq"];
    var regioRotterdam = ["rotterdam", "rdam", "rtm"];
    var regioGestel = ["michielsgestel", "michiels", "sint", "gestel"];
    var regioVoorburg = ["voorburg", "voorbrug"];
    var regioOverig = ["overig", "andere", "etc"];
    var regioGemengd = ["gemengd", "mix", "dooreen"];

Wat betreft woorden als "wijf", ik heb gewoon de synoniemen voor "vrouw" uit het woordenboek overgenomen, zonder zelf te oordelen of het al dan niet ongepast is. Verder zal niemand de woorden zien tot men ze zelf ingeeft - of de broncode bekijkt. Als je bepaalde woorden toch wil verwijderen, laat het even weten.

**Comment by ocrasborn** [comment]
Haha, wat een mooie lijsten @signfuse! Ik begrijp dat ze zo uit het woordenboek komen ('basserool'': nog nooit van gehoord; Vlaams?), maar laten we de meer pejoratieve toch maar weghalen, voordat mensen er mee gaan spelen en klagen: wijf, mannin, gast, kinkel, pief, snuiter
Drie verzoekjes nog:
* 'meisje', 'meid' en 'jongen' erbij bij de geslachten
* 'combi' en 'combinatie' erbij bij regioGemengd
* 'stmichielsgestel' erbij bij regioGestel

**Comment by signfuse** [comment]
Hier de aangepaste lijsten;

    var geslachtMan = ["man", "baas", "basserool", "bink", "broger", "heer", "heerschap", "kadee", "kerel", "manspersoon", "meneer", "mijnheer", "vent", 'jongen'];
    var geslachtVrouw = ["vrouw", "dame", "juffrouw", "mevrouw", "vrouwmens", "vrouwspersoon", 'meisje', 'meid'];
    var regioAmsterdam = ["amsterdam", "adam", "ams"];
    var regioGroningen = ["groningen", "grun", "grq"];
    var regioRotterdam = ["rotterdam", "rdam", "rtm"];
    var regioGestel = ["michielsgestel", "michiels", "sint", "gestel", 'stmichielsgestel'];
    var regioVoorburg = ["voorburg", "voorbrug"];
    var regioOverig = ["overig", "andere", "etc"];
    var regioGemengd = ["gemengd", "mix", "dooreen", 'combi', 'combinatie'];

**Comment by ocrasborn** [comment]
Dank! (ik zie nu dat ik dit in de admin zelf kan aanpassen; fijn!)
