### ISSUE TITLE
Nieuwe lijst aanmaken zou met één klik moeten kunnen

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#29]
Klikken op "Maak een nieuwe lijst aan” (als er nog geen is, nadat ik bij de video heb geklikt op “Sla deze video op in een lijst”) leidt niet direct tot de pagina waar dat kan, maar tot een pagina waar ik opnieuw moet klikken op een knop "Nieuwe videolijstmaken”. Zou direct moeten zijn.

**Comment by signfuse** [comment]
Het wordt nu direct gedaan, maar de video wordt dan niet toegevoegd. Ik heb hier nog even werk aan.

**Comment by signfuse** [comment]
In orde gemaakt
