### ISSUE TITLE
Mogelijkheid om gebruiker zijn eigen account laten editen

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#31]
* Menu item 'Mijn account' rechtsboven? Of de voor/achternaam van de gebruiker?
* Zou meteen gebruikt kunnen worden om weer te geven wie er is ingelogd? (Zie issue #30 , waar het onhandig was dat ik niet wist hoe ik was ingelogd)

**Comment by signfuse** [comment]
Ik heb een menu-item toegevoegd dat dit mogelijk zou moeten maken (bovenaan rechts)

**Comment by ocrasborn** [comment]
Prima @signfuse !
