### ISSUE TITLE
Loze bullet weg bij aanmaken (eerste?) lijst

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#32]
Als ik een video wil toevoegen aan een lijst en er is nog geen lijst, verschijnt de link ‘Maak een nieuwe lijst aan’ in een bulleted list, waar achter de eerste bullet niks staat. Die bullet kan dus weg in dit geval. (Ik neem aan dat het een placeholder is voor de eerste lijst die er aan komt?)

**Comment by signfuse** [comment]
Dit wordt vanzelf opgelost doordat er meteen een nieuwe lijst gemaakt kan worden (zie issue #29 )
