### ISSUE TITLE
Rol beheerder in systeem kunnen testen

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#33]
* De mail na registratie meldt in de subject "wachtend op de goedkeuring van de beheerder", maar het is me niet duidelijk wat ik als beheerder straks zou moeten zien of doen in het systeem. Kun je een test-beheerders-account voor me aanmaken om dat te testen?
* Ik twijfel nog of we deze stap van goedkeuring wel moeten willen, betekent veel extra werk misschien. Ik verwacht zeker 100 nieuwe aanvragen per jaar straks, en in het begin tussen 250-1000. We zouden in plaats daarvan accounts kunnen de-activeren als ze een tijd niet gebruikt zijn? Of heb jij een ander idee?

**Comment by signfuse** [comment]
- Ik zet een beheerderspagina voor je op

- Ik ervaar best veel spam-accounts in websites uit het verleden.

Een oplossing zou kunnen zijn dat we reCAPTCHA v3 gebruiken, maar het is natuurlijk ook een vervelende filter. Mensen moeten dan auto's of verkeerslichten aanduiden in foto's.
Maar dit is ongeveer de enige filter die echt werkt. Dan kan je wel geen aparte rollen automatisch laten toekennen voor tolk - cursist - student

Omgekeerd als je zelf de echte mensen uit de spamaccounts moet filteren, ben je ook wel even bezig. Ik denk dat na een tijd 95% van de registraties spam is. Dit kan wel lager gemaakt worden met een eenvoudige captcha (overtypen van een code) bij registratie van de gebruikers

**Comment by signfuse** [comment]
De beheerderspagina is opgezet. De gebruiker onnocras heeft rechten.
Kan je kijken of alles naar wens verloopt hier?

**Comment by ocrasborn** [comment]
@signfuse , ja, geloof dat alles goed gaat.

**Comment by ocrasborn** [comment]
Oh, en nog over de spam: laten we het even aankijken. We beginnen gewoon, en als er teveel rommel komt, bouwen we alsnog een captcha in.
