### ISSUE TITLE
Foutmelding na bevestiging registratie

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#34]
Bij bevestiging registratie, na invullen metadatavelden, komt er een foutmelding: "Geen toegang. U heeft geen toegangsrechten voor deze pagina." Hier zou iets gebruikersvriendelijkers moeten komen.

**Comment by signfuse** [comment]
Dit kom ik niet tegen. Ik reproduceer;

- ik doe een incognito venster open en ga naar de site.
- Ik klik op registreren
- ik krijg na registratie het bericht dat ik een mail krijg.
- Ik open de mail en klik op een one-time link
- ik vul de rest in, en klik op "opslaan"
- ik krijg het bericht "De wijzigingen zijn opgeslagen." en zie verder terug dezelfde registratiepagina (ik moet dus zelf navigeren naar de voorpagina, dit zou eventueel automatisch kunnen - maar een foutmelding zie ik niet...)

**Comment by ocrasborn** [comment]
Hm. Ik kan het nu ook niet reproduceren --> in de ijskast ermee.
