### ISSUE TITLE
Naam NGT corpus > Corpus NGT

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#39]
We gebruiken "Corpus NGT" (in die volgorde, met hoofdletter C) als naam voor het corpus. Zou je dat overal willen veranderen waar nu nog "NGT Corpus" staat (in ieder geval in de email na registratie, in subject plus bericht)

**Comment by signfuse** [comment]
Ik heb de algemene site-naam aangepast. Normaal wordt die overal "overgeërfd". Mocht dit ergens niet zo zijn, merk het even op en ik pas het aan.
