### ISSUE TITLE
Kleine wijzigingen in formulier persoonsgegevens

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#40]
* Bewerken formulier persoonsgegevens / ‘confirm registration’ form:
    * leeraar > leraar in menuutje beroep
    * onderaan, veldnamen regeninteresse > Reden interesse; anderereden > Andere reden
    * Veldnamen beroep en startjaar met een hoofdletter

**Comment by signfuse** [comment]
Goed opgemerkt! Ik heb het aangepast
