### ISSUE TITLE
Veld 'Instelling' tot pull-downmenu met opties omvormen

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#41]
* Veld Instelling: i.p.v. tekstveld een menu: HU, RU, UvA, UL, overig
* Lijst redigeerbaar maken via de admin, opdat allerlei docent-bedrijven die hiermee willen werken er later ook in kunnen (en we dat zelf kunnen bijhouden)

**Comment by signfuse** [comment]
Op de planning

**Comment by signfuse** [comment]
Aangepast.
Dit staat nu beschikbaar in het menu van de beheerpagina die doorverwijst naar  http://mine.signfuse.com/admin/structure/taxonomy
