### ISSUE TITLE
Aantal velden meteen bij aanmelding al laten invullen

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#42]
In registration form: bij onderaan, 'Ik geef toestemming’ of zoiets, voor opslaan van alle velden met een *. S.v.p. de volgende velden al bij aanmelding verplicht maken. Veld ‘Startjaar’ alleen tonen als er een instelling wordt geselecteerd:
    * Voor/achternaam
    * Beroep (hernoemen naar 'Ik ben...')
    * Instelling
    * Startjaar

**Comment by signfuse** [comment]
Ik heb de genoemde velden verplicht gemaakt.

**Comment by signfuse** [comment]
Ik heb nu ook het startjaar enkel zichtbaar gemaakt indien er een instelling gekozen wordt (niet "andere")
