### ISSUE TITLE
Andere serif font?

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#45]
Ik vind de geschreefde (serif) font die nu gebruikt wordt niet erg mooi, te hoekig. Heb je een voorstel voor iets zachters?

**Comment by signfuse** [comment]
ok, op de planning

**Comment by signfuse** [comment]
Heb je het hier specifiek over het font op de pop-up pagina's? Dan ben ik helemaal mee, en denk ik dat er ook wat meer witruimte bij kan, het plakt nog wat op elkaar...

Maar als je het hebt over de gewone pagina's, kan je dan iets meer duiden?

**Comment by signfuse** [comment]
ik denk dat ik ondertussen begrepen heb wat je bedoelde. ik heb wat met de fonts gespeeld.

**Comment by ocrasborn** [comment]
@signfuse Haha, en intussen is het weer ruim drie maanden verder en ben ik zelf vergeten hoe het er eerder uitzag. Ik zie nu niks wat me stoort, dus gooi deze dicht :-)
