### ISSUE TITLE
Hernoemen categorie 'Collega's' naar 'Gebruikers'

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#46]
Collega’s hernoemen tot ‘Gebruikers’ (opdat het zowel docenten als cursisten/studenten dekt) -- of weet jij nog een beter alternatief?

**Comment by signfuse** [comment]
Nee, ik weet geen beter alternatief, ik had het initieel ook Gebruikers genoemd zie ik aan de systeemnaam (die is gebruikers). Om een of andere reden heb ik het daarna hernoemd naar collega's. Misschien klonk gebruikers me wat te onpersoonlijk.
