### ISSUE TITLE
Duur van een filmpje wordt nog niet weergegeven

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#48]

**Comment by signfuse** [comment]
Ontbreekt in de json metadata (Metadata_participants_sessions_OC.json)
Nodig; duur filmpje, al dan niet beschikbaar zijn van glos en vertaling

**Comment by ocrasborn** [comment]
@signfuse Even kijken... ik zie nu wel al in de detail-weergave van een filmpje de duur verschijnen, maar nog niet in de lijst-weergave. Ik begrijp dus dat we ze inmiddels in de json hebben aangeleverd. Heb jij een voorstel over waar we dat zouden kunnen weergeven, zonder dat het visueel te rommelig wordt? Wellicht tussen rechte haken in de link na de titel? Dan krijgen we iets als  CNGT0657 – Tweety & Sylvester [0:48]

**Comment by signfuse** [comment]
@ocrasborn  Ah, je wil het ook in de lijst-weergave. Dat hebben we niet aangegeven in ons prototype.
Ik heb het iets grafischer aangepakt, de duur wordt over de afbeelding weergeven.
Lijkt je dat goed?

Ik moest hiervoor op verschillende plaatsen iets bijwerken (er zijn zoveel verschillende soorten lijst-weergaves), dus als het ergens zou ontbreken, laat zeker even weten!

**Comment by signfuse** [comment]
![Schermafbeelding 2020-04-28 om 16 06 31](https://user-images.githubusercontent.com/19531551/80497212-6eff8680-896a-11ea-934c-b5df481c6077.png)

**Comment by ocrasborn** [comment]
Ah, dat wist ik niet meer van dat prototype, maar fijn dat je het nu toegevoegd hebt. Helemaal prima zoals het nu gevisualiseerd is. Dit voegt echt iets toe qua gebruikersgenot, denk ik.
