### ISSUE TITLE
Visualisering in lijst met zoekresultaten of er vertalingen en of er glossen beschikbaar zijn

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#49]

**Comment by ocrasborn** [comment]
Voorstel: twee verschillende icoontjes in het midden van de video-still in de lijst, opdat het in één oogopslag duidelijk wordt als je door de lijst scrollt. Alternatief: rechtsonder in het vak, onder de sterren?

**Comment by signfuse** [comment]
Mee eens! Maar zoals ik elders al schreef ontbreekt deze informatie in de json metadata die Micha me stuurde. Kan dit aangepast worden? (ook duur van de video ontbreekt daar)

**Comment by ocrasborn** [comment]
Even kijken... Ik heb je dus de VTT's opnieuw gemaild, maar daar gaat het eigenlijk niet om, begrijp ik: we moeten zorgen dat in de json per sessie (0001 t/m 2375) velden bij komen voor 'is vertaald' en 'is geglost', begrijp ik dat goed, @signfuse ?

**Comment by signfuse** [comment]
Klopt @ocrasborn het gaat niet over de ondertitels, maar over de metadata van de sessies.
Het bestand dat ik kreeg noemde Metadata_participants_sessions_OC.json
Inderdaad zouden daar deze velden mogen verschijnen, maar ook het veld "duurtijd", de lengte van het filmpje in seconden.

**Comment by signfuse** [comment]
Gebeurd!

**Comment by ocrasborn** [comment]
@signfuse Ziet er mooi en duidelijk uit zo, met nog één verzoek daarbij: om in plaats van een T (translation) een V (vertaling) weer te geven.

**Comment by signfuse** [comment]
Tuurlijk, waarom had ik er toch een T van gemaakt? Ik zal wel verstrooid geweest zijn. Is aangepast.

**Comment by ocrasborn** [comment]
Er zit nog ergens een foutje: #63 , maar ik zal deze afsluiten nu. Dank!
