### ISSUE TITLE
Zoek-suggestie verplaatsen

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#51]
In de zwarte tijdlijn-balk staat nu de tekst "Zoek bv. naar woorden die in de lijst rechts verschijnen." Hij wekt de indruk dat je daar kunt klikken, maar het gaat over het glos-veld. Als je er op klikt verspringt immers de video naar een andere tijd.
Ik denk dat we op meer plekken een hulp-ballonnetje zullen kunnen gebruiken; wat mij betreft door kleine ballonnetjes met een vraagteken bij hover-over een pop-up met een kort tekstje zoals de bovenstaande te laten zien. In dit geval rechts(boven) naast de zoek-pijl?

**Comment by signfuse** [comment]
op de planning

**Comment by signfuse** [comment]
ik heb ze verplaatst naar de verzend-knop (mouse-over)
