### ISSUE TITLE
Metadata over filmpje ook in kader

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#52]
Bij de weergave van een filmpje staan de persoons-metadata met de still in een kader, terwijl de film-metadata (bv.: Een herinnering Monoloog Duur:) op één rij ertussen staan. Ik denk dat het rustiger wordt als ook die in een gecentreerd kader van dezelfde grootte staan, met de drie velden op een rij in plaats van na elkaar. Even uitproberen? Of gewoon de tekst in drie rijen gecentreerd er tussen in?

**Comment by signfuse** [comment]
Ik heb het in een kader gezet. Is responsief wel nog niet goed opgelost, daar kijk ik op een later moment nog even naar. Maar je kan al bekijken of het voor jou de goede kant op gaat zo (in een groot venster).

**Comment by ocrasborn** [comment]
yes, op m'n desktop ziet het er goed uit, mooi
