### ISSUE TITLE
Wijzigen tekst bevestiging gloss-suggestie

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#53]
* De tekst luidt nu: "Uw suggestie voor het wijzigen van de gloss [PO] naar [ditIsEenTestSuggestie] werd verzonden naar de verantwoordelijke. Hartelijk dank voor uw bijdrage."
* Svp wijzigen naar "...werd opgeslagen. Eens in de zoveel maanden worden deze suggesties verwerkt door de Radboud Universiteit."
* Iets anders: deze pop-up heeft nu een titel, maar het windowtje waarin die staat heeft dezelfde titel; een van de twee mag weg.

**Comment by signfuse** [comment]
- De tekst is aangepast

- Goed gezien! Ik heb de pop-up titel aangepast
