### ISSUE TITLE
Tags is nog geen lijst; icoontje toevoegen

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#54]
* De interface suggereert van wel, als je op een tag klikt verschijnt nl. een lijst met zoekresultaten.
* De resulterende bevat gele items, net als zoek-lijsten, maar bij zoeklijsten zie ik niet mijn tag. Het lijkt me ook goed om deze gescheiden te houden.

**Comment by signfuse** [comment]
- Ja, snap ik. Maar zou je nu liever zien dat tags ook als lijsten worden opgeslagen, of dat de layout van tags anders gemaakt wordt, zodat het duidelijker is dat het geen lijst is?

- Die kleur zou inderdaad niet moeten overeenkomen. Mooi punt.

**Comment by signfuse** [comment]
ik heb de kleur aangepast (van geel naar marineblauw)

**Comment by ocrasborn** [comment]
Dank, prima zo. De tags functioneren nu als lijsten, als je er op klikt krijg je alle sessies met die tag. Alleen zijn de tags nog niet op een rijtje te zien onder 'Mijn lijsten', is dat ook wat je bedoelde in je vraag? Het lijkt mij handig voor de gebruiker als er onder Mijn lijsten onderaan ook een item Tags staat (onder Video's, Gebaarders, Gebruikers, Zoekfuncties), waarin gebruikers kunnen zien welke ze in gebruik hebben, en door er op te klikken naar de lijst met video's met die tag gaan.

**Comment by signfuse** [comment]
Goed idee

**Comment by signfuse** [comment]
Ik heb de lijst tags aangemaakt, moet nog een icoontje bedenken voor het menu - suggestie?

"Tags" wordt op een bepaald moment door het systeem vertaald naar "labels". Haal ik de vertaling eruit, of hernoemen we de rest naar "labels"?

Op dit moment ziet ieder elkaars tags. Is dit de bedoeling, of zie je het liever privé?

**Comment by ocrasborn** [comment]
Ik dacht aan zoiets, maar dan horizontaal Een bagagelabel.
![image](https://user-images.githubusercontent.com/10242207/78376750-0cb3a000-75cf-11ea-80f1-2eb6d15ae2bf.png)
![image](https://user-images.githubusercontent.com/10242207/78376657-e857c380-75ce-11ea-9b67-de5b54116697.png)

**Comment by ocrasborn** [comment]
Deze misschien?
![Tag](https://user-images.githubusercontent.com/10242207/78387445-a3885880-75df-11ea-9182-6ea7586e4bf3.png)

**Comment by signfuse** [comment]
ik heb een icoontje toegevoegd

![tagico](https://user-images.githubusercontent.com/19531551/80496774-ef71b780-8969-11ea-9156-8ee0af03f6a5.png)

![tagicoar](https://user-images.githubusercontent.com/19531551/80496832-ff899700-8969-11ea-97d3-2bcf3f277818.png)

**Comment by signfuse** [comment]
@ocrasborn Deze vragen staan nog open;

"Tags" wordt op een bepaald moment door het systeem vertaald naar "labels". Haal ik de vertaling eruit, of hernoemen we de rest naar "labels"?

Op dit moment ziet ieder elkaars tags. Is dit de bedoeling, of zie je het liever privé?

**Comment by ocrasborn** [comment]
@signfuse : mooier, die kleine grijze, prima
De antwoorden:
* Laten we alles maar naar 'label' hernoemen
* De labels moeten privé zijn

**Comment by ocrasborn** [comment]
@signfuse : bij "mijn lijsten" staat nog 'tag' in plaats van 'label'

**Comment by signfuse** [comment]
gedaan, alsook op de videopagina (daar stond: "voeg uw tags toe")
