### ISSUE TITLE
Meer glossen weergeven rechts naast video

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#55]
Omdat de spacing rond de glossen vrij groot is, passen er maar zes glossen in beeld. Dat geeft weinig overzicht, en bij afspelen scrollt de lijst nogal nerveus naar boven. Door de verticale spacing wat kleiner te maken, passen er meer glossen in beeld en wordt het scroll-effect wat rustiger.

**Comment by signfuse** [comment]
Goed punt. Ik heb het aangepast
