### ISSUE TITLE
Wit Radboud-logo rechtsonder aan elke pagina, met link

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#57]
* Zie bijlage voor logo (EPS); niet al te klein weergeven zou ik zeggen
* Graag linken naar http://www.ru.nl/gebarentaal
[ru_nl_a4_wit_2014.eps.zip](https://github.com/signfuse/corpusNGT/files/3740489/ru_nl_a4_wit_2014.eps.zip)

**Comment by signfuse** [comment]
Dit heb ik gedaan. Ik weet niet of de zichtbaarheid goed genoeg is?
Is rechtsonder elke pagina geplaatst

**Comment by ocrasborn** [comment]
Ik zie het. Niet zichtbaar dus :-) Dan maar liever de zwarte. 
[ru_nl_a4_zwart_2014.eps.zip](https://github.com/signfuse/corpusNGT/files/3961248/ru_nl_a4_zwart_2014.eps.zip)

**Comment by signfuse** [comment]
ik heb het vervangen
