### ISSUE TITLE
Aanpassing layout zoekpagina

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#61]
Een aantal kleine verzoekjes voor de pagina Geavanceerd Zoeken:
* Beetje spatie toevoegen boven Trefwoorden invoeren en het zoekvak ernaast, opdat het los komt te staan van de menubalk* Maak de knop "Zoeken" niet veel breder dan het woord Zoeken (20px aan elke kant?)
* Plaats de knop rechts van het zoekvak _Trefwoorden invoeren_
* Hernoem "Trefwoorden invoeren" naar "Woorden uit glossen of vertalingen" -- tenminste, even checken: klopt dat? wordt er inderdaad ook zowel de vertalingen als de glossen gezocht? Misschien sowieso beter die twee te scheiden, twee zoekvakken te maken.

**Comment by ocrasborn** [comment]
De eerste twee lijken me afgehandeld, doe jij de derde nog @signfuse ?

**Comment by signfuse** [comment]
done
