### ISSUE TITLE
Foutje in weergave "G" symbool voor gegloste sessies

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#63]
- In zoekresultaten wordt nu onterecht voor _alle_ sessies een G weergegeven.
- Als ik vanaf de homepage een persoon aanklik, wordt wel correct de G weergegeven voor alleen de gegloste sessies

**Comment by signfuse** [comment]
Goed gezien! Foutje. Bij deze opgelost veronderstel ik.

**Comment by ocrasborn** [comment]
inderdaad! :-)
