### ISSUE TITLE
Kopje "keyword-search" mag weg

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#64]
Dit verschijnt bovenaan de lijst met zoekresultaten als ik bij Geavanceerd zoeken een term heb ingevoerd en op zoeken geklikt; lijkt me redundant (hoewel het eigenlijk vooral opviel doordat het in het Engels is, en men net op "trefwoord" heeft gezocht, niet "keyword" :-)).
Maar even terzijde: wat een geweldige visualisatie van de zoek-hit!! Complimenten!

<img width="1165" alt="Screenshot 2020-05-14 17 32 58" src="https://user-images.githubusercontent.com/10242207/81954645-64e7b400-9609-11ea-8567-9481f4d0c1b2.png">

**Comment by signfuse** [comment]
Ik heb er nu "Zoeken op trefwoord" van gemaakt. Of heb je liever geen titel?

Dank je voor de complimenten.
Ik zie nu wel dat er een 0 staat ipv de sterren. Dat moet ik even rechtzetten.

Nu worden er 5 resultaten getoond. Hoeveel mogen er uiteindelijk per pagina weergegeven worden?

**Comment by ocrasborn** [comment]
"Zoeken op trefwoord" is prima, dankjewel.
Oh ja, die 0, die was me in de opwinding van de hit-visualisatie niet eens opgevallen!
Over het aantal resultaten, @signfuse : maak daar maar vijftig van, ik begin steeds meer allergisch te worden voor paginering met korte lijsten, bv in webwinkels. We gaan eens kijken hoe onze server daar mee om gaat.

**Comment by ocrasborn** [comment]
Worden het er dan vijftig, punt? Of vijftig per pagina, en het totaal aantal resultaten boven de lijst in beeld (Resultaten 1-50, 51-100, ...)?

**Comment by signfuse** [comment]
normaal gezien wordt het gepagineerd (50 per pagina), maar dat moet ik er nog inbouwen.

**Comment by signfuse** [comment]
dus je gaat voor 50?

**Comment by ocrasborn** [comment]
Nou ja, ik zou zeggen: toegang tot alle resultaten mogelijk maken, en daarbij gepagineerd weergeven met een vaste grootte van 50 per pagina.

**Comment by signfuse** [comment]
gebeurd

**Comment by ocrasborn** [comment]
Nog een detail, @signfuse : de punt in de zin naar het eind verplaatsen. Dus niet:
Resultaten worden hieronder weergegeven. (max 50 per pagina)
Maar:
Resultaten worden hieronder weergegeven (max 50 per pagina).

Taalkundige, he ;-)

**Comment by signfuse** [comment]
Goed punt (!).
Is aangepast.
