### ISSUE TITLE
Statische pagina "Hulp" invoegen in hoofdmenu tussen Mijn Lijsten en Hallo [gebruikersnaam]

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#65]
Ik merk dat we zowel voor de functies van de site als voor de achtergrond over de annotaties informatie moeten verschaffen. Het lijkt me goed om die prominent aanwezig te hebben. Als jij een blanco pagina maakt die ik in de admin kan invullen, kunnen we dat makkelijk onderhouden en uitbreiden aan de hand van ervaringen en vragen van gebruikers.

**Comment by ocrasborn** [comment]
Zodra deze pagina er is, durf ik een paar testers naar de site te laten kijken, want dan kan ik ze wat basis-uitleg geven, en op basis van hun feedback die pagina verder gaan vullen.

**Comment by signfuse** [comment]
@ocrasborn Ik heb de pagina aangemaakt, je zou ze in het menu moeten terugvinden.
Je kan de pagina bewerken als je inlogt als "onnocras"

**Comment by ocrasborn** [comment]
Ik mag wel de titel wijzigen, maar in het veld body heb ik nog geen rechten, lees ik in het lichtgrijs. Pas je dat nog even aan @signfuse ?

**Comment by ocrasborn** [comment]
Kan ik er trouwens html in schrijven, of licht-gemarkup-te tekst?

**Comment by signfuse** [comment]
inderdaad html - probeer je nog eens?

**Comment by ocrasborn** [comment]
top!
