### ISSUE TITLE
Zoeken met de slider

### ISSUE THREAD

**Issue by signfuse** [signfuse/corpusNGT#67]
Je kan nu zoeken op gebaarsnelheid, aantal gebaren, etc met behulp van een slider.
Maar die slider geeft dus een nummer aan, pak als voorbeeld 70.03%.

Dus als we 70.03% snelheid zoeken, hoe exact moet dat zijn?
Willen we dan een range (bv 65 à 75 %) of alles boven 70.03%?

We moeten er ook rekening mee houden dat we een standaardwaarde moeten kunnen aangeven met de slider die ALLE resultaten geeft, ongeacht bv de snelheid van de gebaarder. Zodat de bezoeker kan zoeken op alle mannen uit Amsterdam ongeacht de gebaarsnelheid. Dan is een range eerder beperkend, en een "groter dan" is dan veel ruimer (bv alles boven 0% indien alles - of alles boven 70.03% indien zoekend op snelheid)

**Comment by ocrasborn** [comment]
* Ik denk dat het meest intuïtief is om een ruime range van zeg 10% te pakken.
* Dit is iets van op de info-pagina uitleg kan krijgen, maar ik moet me eerst zelf weer even verdiepen in de data, hoe we die gemaakt hebben. Voor de niet-geannoteerde filmpjes hebben we nl. geëxtrapoleerd op basis van filmpjes die wel geannoteerd waren.
* Ik speelde er net even mee, en merk dat de rechterhelft van de classifier-slider tot nul resultaten leidt. Maar was het niet zo dat we waren uitgegaan van het spectrum van gevonden waardes binnen de bestanden, en dat dus voor alle sliders elke plek op de slider tot min. één hit zou moeten leiden?
* Inderdaad ja: mensen zouden de slider ook weer moeten kunnen resetten opdat alles weergegeven wordt. Heb jij hier een idee voor? Een reset-knop voor alle sliders tegelijk?
* Als default (bij geen selectie, of na een reset) lijkt het me intuïtiever als de knop overal in het midden staat, niet? Meer naar links betekent dan 'minder dan gemiddeld', meer naar rechts 'meer dan gemiddeld'.

**Comment by signfuse** [comment]
ik heb het geavanceerd zoeken aangepast, met inbegrip van de sliders.
Ik heb een range van 10% genomen. En de slider naar links schuiven, zet ze uit.

De laatste slider (lokale gebaren) werkt niet, wegens geen data.

**Comment by ocrasborn** [comment]
Goed idee zo met die getallen erbij. Ik ga nog aan de data-kant werken.
