### ISSUE TITLE
Sessienummer toevoegen aan detail-pagina video

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#71]
Een klein dingetje: bij het bekijken van een video is nu niet het volgnummer te zien (CNGT0253 bv.). Voorstel: deze bovenaan toevoegen in het blokje metadata waar nu bv. staat 'Tweety & Sylvester', 'Monoloog', en 'Duur'.
Mooi bij-effect: alle drie de blokjes hebben dan vier regels, mooi opgelijnd.

**Comment by signfuse** [comment]
Dit is gebeurd. Ik kan me voorstellen dat je daar ook iets vet of onderlijnd zou willen zien? Iets meer opmaak?

**Comment by ocrasborn** [comment]
Eh, nee, lijkt me rustiger zonder verdere opmaak. Maar kun je wel afdwingen dat de drie blokjes precies even hoog zijn? De middelste heeft nu meer spatie boven/onder, is niet mooi. Of vond jij van wel, en was het bewust?! :-) Ikdenk dat het rustiger oogt als ze precies even hoog zijn.

**Comment by signfuse** [comment]
Ik had het precies zo gedaan als je het beschrijft, maar blijkbaar zie jij nog de oude versie.
Kan je refreshen?

**Comment by ocrasborn** [comment]
yes, opgelost. Gewoon shift-reload in safari werkte niet, even cache geleegd, nu is het... beeldschoon! ;-)
