### ISSUE TITLE
Oplijning metadata soms niet goed

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#73]
Bij een aantal filmpjes belandt het derde blokje metadata (voor de rechtergebaarder) op een nieuwe regel, lijkt het. Bv. sessie 95 t/m 99. Zie bv. http://mine.signfuse.com/corpusvideo/144
Hoe ik m'n scherm ook re-size, het blijft verstoord.

**Comment by signfuse** [comment]
klopt, heb ik hier ook al een hele tijd. Geen prioriteit van gemaakt.

**Comment by signfuse** [comment]
is bijgewerkt hopelijk - ik hou het in het oog bij de andere videos die ik tegenkom.

**Comment by ocrasborn** [comment]
Geloof 't ook! als we nog iets tegenkomen, laten we het weten. Uit nieuwsgierigheid: wat was de oorzaak? Ik zie niet echt verschil in tekst-lengte of zo

**Comment by signfuse** [comment]
![Schermafbeelding 2020-06-06 om 13 32 48](https://user-images.githubusercontent.com/19531551/83943184-3de06480-a7fa-11ea-8e69-5a90e41eebe9.png)

Het was nogal strak afgelijnd. Nu is enkel links nog een vaste afstand gezet (zie geel in screenshot), daarvoor was er rechts ook dezelfde vaste afstand (die echt niet nodig is want de rechterbox is sowieso helemaal rechts uitgelijnd).
Als oplossing heb ik de marge aan de rechterkant nul gemaakt, waardoor de rechterbox niet weggeduwd wordt als de tekst in de middelste box net iets te lang wordt - ik vermoed dat dat de tekst "Discussion (Deaf issues)" is in jouw voorbeeld, en "Spot the differences" in het screenshot.

**Comment by ocrasborn** [comment]
Dankjewel, leuk om te weten!
