### ISSUE TITLE
Kleine blauwe pijltje bij actieve lijst wat groter maken

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#74]
In de linkerkolom bij Lijsten staat de lijst-categorie die nu is aangeklikt gemarkeerd met een heel klein blauw pijltje. Het is enerzijds redundant, rechts zie je immers wat actief is, maar ik vind het toch wel heel mooi en duidelijk. Alleen: kan hij ietsje groter, die pijl?

**Comment by signfuse** [comment]
Zo?
Voor afbeeldingen is het wel flink refreshen ("harde refresh"), is meestal de shift-toets ingedrukt houden terwijl je refresht.

**Comment by ocrasborn** [comment]
Top, @signfuse !
