### ISSUE TITLE
Woord "Hallo" weg bij gebruikersnaam in menubalk

### ISSUE THREAD

**Issue by ocrasborn** [signfuse/corpusNGT#75]
De eerste tester (Merel) liep er meteen tegenaan, ik vond het zelf ook niet ideaal: dat "Hallo onnocras" in de menubalk (in mijn geval dan). Het "Hallo" suggereert dat daar een welkomstwoord staat, maar dat is niet zo, het is de profielpagina. Voorstel: gewoon 'Hallo' weg; de gebruikersnaam is voldoende om aan te geven waar het om gaat, zo werken alle webwinkels ook bv.

**Comment by signfuse** [comment]
Zo!
